name: Blake Denman
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f17e45'
    - '#fefefe'
    - '#000000'
    - '#adadad'
    - '#5b5b5b'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
