name: Blake Denman
favicon: null
layout_spectrum: 0.756768707651645
typography_spectrum: 0.4494178092572838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4099301160313189
  lightness: 0.7281121755950153
  saturation: 0.7520710488315672
  rhythmicContrast: 0.594226379878819
purpose: []
