name: Blake Denman
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f17e45'
    - '#fefefe'
    - '#000000'
    - '#adadad'
    - '#5b5b5b'
  brandStrength: 0.6875
  lightness: 0.7281121755950153
  saturation: 0.7520710488315672
  rhythmicContrast: 0.594226379878819
purpose: []
